---
platform:
  os: linux
  arch: amd64

# Begin
clone:
  git-clone:
    commands: |
      set -ex
      git clone -b ${DRONE_TAG:-$DRONE_BRANCH} $DRONE_REMOTE_URL .
      if [ x$DRONE_PULL_REQUEST != x ]; then
          git fetch origin refs/pull/$DRONE_PULL_REQUEST/head
          EMAIL=ci git merge --no-edit FETCH_HEAD
      fi
      git rev-parse HEAD
    image: "casperlabs/buildenv:latest"

kind: pipeline
name: build-bors-merge

steps:
- name: run-lint
  commands:
  - "make prepare"
  - "make lint"
  image: "casperlabs/buildenv:latest"
  when:
    branch:
    - staging
    - trying
    - master
    event:
    - pull_request
    - push

- name: run-tests
  commands:
  - "make prepare"
  - "make test"
  image: "casperlabs/buildenv:latest"
  when:
    branch:
    - staging
    - trying
    - master
    event:
    - pull_request
    - push
  depends_on:
  - run-lint

trigger:
  branch:
  - master
  - trying
  - staging

---
kind: pipeline
name: failed-build-alert

clone:
  disable: true

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    template:
    - |
      erc2-repo build status: *{{ uppercasefirst build.status }}*
      Author: {{ build.author }}
      Drone Build: <{{ build.link }}|#{{ build.number }}>
      Commit Link: <https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}|{{ truncate build.commit 10 }}>
trigger:
  status:
  - failure
  branch:
  - master
  - trying
  - staging

depends_on:
- build-bors-merge
