//! Constants used by the ERC1155 contract.
/// Name of dictionary-key for `erc1155_token_contract`
pub const ERC1155_TOKEN_CONTRACT_KEY_NAME: &str = "erc1155_token_contract";
/// Name of dictionary-key for `allowances`
pub const ALLOWANCES_KEY_NAME: &str = "allowances";
/// Name of named-key for `tokens`
pub const TOKENS_KEY_NAME: &str = "tokens";
/// Name of `balance_of` entry point.
pub const BALANCE_OF_ENTRY_POINT_NAME: &str = "balance_of";
/// Name of `balance_of_batch` entry point.
pub const BALANCE_OF_BATCH_ENTRY_POINT_NAME: &str = "balance_of_batch";
/// Name of `safe_transfer_from` entry point.
pub const SAFE_TRANSFER_FROM_ENTRY_POINT_NAME: &str = "safe_transfer_from";
/// Name of `safe_batch_transfer_from` entry point.
pub const SAFE_BATCH_TRANSFER_FROM_ENTRY_POINT_NAME: &str = "safe_batch_transfer_from";
/// Name of `approve` entry point.
pub const SET_APPROVAL_FOR_ALL_ENTRY_POINT_NAME: &str = "set_approval_for_all";
/// Name of `allowance` entry point.
pub const IS_APPROVAL_FOR_ALL_ENTRY_POINT_NAME: &str = "is_approval_for_all";
/// Name of `transfer_from` entry point.

/// Name of `address` runtime argument.
pub const ADDRESS_RUNTIME_ARG_NAME: &str = "address";
/// Name of `address` runtime argument.
pub const APPROVED_RUNTIME_ARG_NAME: &str = "approved";
/// Name of `address` runtime argument.
pub const ACCOUNTS_RUNTIME_ARG_NAME: &str = "accounts";
/// Name of `amount` runtime argument.
pub const AMOUNT_RUNTIME_ARG_NAME: &str = "amount";
/// Name of `amounts` runtime argument.
pub const AMOUNTS_RUNTIME_ARG_NAME: &str = "amounts";
/// Name of `recipient` runtime argument.
pub const OWNER_RUNTIME_ARG_NAME: &str = "owner";
/// Name of `spender` runtime argument.
pub const SPENDER_RUNTIME_ARG_NAME: &str = "spender";
/// Name of `token_id` runtime argument.
pub const TOKEN_ID_RUNTIME_ARG_NAME: &str = "token_id";
/// Name of `token_ids` runtime argument.
pub const TOKEN_IDS_RUNTIME_ARG_NAME: &str = "token_ids";
/// Name of `recipient` runtime argument.
pub const RECIPIENT_RUNTIME_ARG_NAME: &str = "recipient";
